# Generated by Django 2.1.3 on 2018-12-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MAC',
        ),
        migrations.RemoveField(
            model_name='mcqoption',
            name='MCQ_id',
        ),
        migrations.RemoveField(
            model_name='optionvoting',
            name='MCQ_id',
        ),
        migrations.RemoveField(
            model_name='questionvoting',
            name='question_id',
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.DeleteModel(
            name='MCQOption',
        ),
        migrations.DeleteModel(
            name='OptionVoting',
        ),
        migrations.DeleteModel(
            name='QuestionVoting',
        ),
    ]
