# Generated by Django 2.1.3 on 2018-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20181204_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isAnswered',
            field=models.BooleanField(default=False),
        ),
    ]
