# Generated by Django 2.1.3 on 2018-12-10 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_question_isanswered'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timeStamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
