# Generated by Django 2.1.3 on 2018-12-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_question_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
